name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup

      - run: yarn nx run @dot-connect/docs:build

      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dot-connect
          directory: apps/docs/.vitepress/dist
