name: Verification

on: [workflow_call, workflow_dispatch]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: yarn prettier --check .
      - run: yarn lint
      - run: yarn build
